from fastapi import APIRouter

from app.api.v1 import ai, appointments, auth, batteries, billing, catalog, clinical, dashboard, instruments, me, patients, prontuario, sessions, spm, spm_informant, timeline, webhooks, whatsapp

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(billing.router)
api_router.include_router(me.router)
api_router.include_router(catalog.router)
api_router.include_router(patients.router)
api_router.include_router(appointments.router)
api_router.include_router(sessions.router)
api_router.include_router(sessions.patient_router)
api_router.include_router(prontuario.router)
api_router.include_router(timeline.router)
api_router.include_router(timeline.patient_router)
api_router.include_router(clinical.router)
api_router.include_router(clinical.patient_router)
api_router.include_router(instruments.router)
api_router.include_router(batteries.router)
api_router.include_router(spm.router)
api_router.include_router(spm_informant.router)
api_router.include_router(dashboard.router)
api_router.include_router(ai.router)
api_router.include_router(whatsapp.router)
api_router.include_router(webhooks.router)
