"""Protocol catalog seed data — mirrors frontend mock-data.ts protocolsCatalog."""

PROTOCOLS = [
    {
        "id": "abfw",
        "name": "ABFW",
        "full_name": "Teste de Linguagem Infantil ABFW",
        "description": "Avaliação de fonologia, vocabulário, fluência e pragmática.",
        "age_range": "2 a 12 anos",
        "field_templates": [
            {"key": "fonologia_imitacao", "label": "Fonologia — imitação"},
            {"key": "fonologia_nomeacao", "label": "Fonologia — nomeação"},
            {"key": "vocabulario_expressivo", "label": "Vocabulário expressivo"},
            {"key": "fluencia", "label": "Fluência"},
            {"key": "pragmatica", "label": "Pragmática"},
        ],
    },
    {
        "id": "proc",
        "name": "PROC",
        "full_name": "Protocolo de Observação Comportamental",
        "description": "Observação de comunicação, linguagem e cognição.",
        "age_range": "0 a 6 anos",
        "field_templates": [
            {"key": "atencao_compartilhada", "label": "Atenção compartilhada"},
            {"key": "intencao_comunicativa", "label": "Intenção comunicativa"},
            {"key": "compreensao_verbal", "label": "Compreensão verbal"},
            {"key": "jogo_simbolico", "label": "Jogo simbólico"},
        ],
    },
    {
        "id": "tvip",
        "name": "TVIP",
        "full_name": "Teste de Vocabulário por Imagens Peabody",
        "description": "Avaliação do vocabulário receptivo auditivo.",
        "age_range": "2 a 18 anos",
        "field_templates": [
            {"key": "pontuacao_bruta", "label": "Pontuação bruta"},
            {"key": "idade_equivalente", "label": "Idade equivalente"},
            {"key": "percentil", "label": "Percentil"},
            {"key": "classificacao", "label": "Classificação"},
        ],
    },
    {
        "id": "mchat",
        "name": "M-CHAT",
        "full_name": "Modified Checklist for Autism in Toddlers",
        "description": "Rastreamento de risco para o espectro autista.",
        "age_range": "16 a 30 meses",
        "field_templates": [
            {"key": "itens_criticos", "label": "Itens críticos falhados"},
            {"key": "total_falhas", "label": "Total de falhas"},
            {"key": "nivel_risco", "label": "Nível de risco"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "ados2",
        "name": "ADOS-2",
        "full_name": "Autism Diagnostic Observation Schedule — 2nd Edition",
        "description": "Instrumento de observação padronizada para diagnóstico de TEA.",
        "age_range": "12 meses a adultos",
        "field_templates": [
            {"key": "comunicacao", "label": "Comunicação"},
            {"key": "interacao_social", "label": "Interação social recíproca"},
            {"key": "brincadeira", "label": "Brincadeira/imagi. criativa"},
            {"key": "comportamentos_repetitivos", "label": "Comportamentos repetitivos"},
            {"key": "classificacao", "label": "Classificação"},
        ],
    },
    {
        "id": "cars",
        "name": "CARS",
        "full_name": "Childhood Autism Rating Scale",
        "description": "Escala de avaliação do comportamento para diagnóstico e gravidade do autismo infantil.",
        "age_range": "2 a 15 anos",
        "field_templates": [
            {"key": "relacionamento", "label": "Relacionamento com pessoas"},
            {"key": "imitacao", "label": "Imitação"},
            {"key": "resposta_emocional", "label": "Resposta emocional"},
            {"key": "uso_corpo", "label": "Uso do corpo"},
            {"key": "score_total", "label": "Score total"},
        ],
    },
    {
        "id": "vbmapp",
        "name": "VB-MAPP",
        "full_name": "Verbal Behavior Milestones Assessment and Placement Program",
        "description": "Avaliação baseada na ABA para habilidades de linguagem e desenvolvimento.",
        "age_range": "18 meses a 4 anos",
        "field_templates": [
            {"key": "mandos", "label": "Mandos (solicitação)"},
            {"key": "tato", "label": "Tato (nomeação)"},
            {"key": "intraverbal", "label": "Intraverbal"},
            {"key": "listener", "label": "Listener responding"},
            {"key": "barreiras", "label": "Barreiras"},
        ],
    },
    {
        "id": "abllsr",
        "name": "ABLLS-R",
        "full_name": "Assessment of Basic Language and Learning Skills — Revised",
        "description": "Avaliação das habilidades básicas de linguagem e aprendizagem.",
        "age_range": "0 a 12 anos",
        "field_templates": [
            {"key": "receptivas", "label": "Habilidades receptivas"},
            {"key": "motoras", "label": "Habilidades motoras"},
            {"key": "sociais", "label": "Habilidades sociais"},
            {"key": "autoajuda", "label": "Autoajuda"},
            {"key": "leitura", "label": "Leitura"},
        ],
    },
    {
        "id": "afls",
        "name": "AFLS",
        "full_name": "Assessment of Functional Living Skills",
        "description": "Avaliação de habilidades funcionais para vida independente.",
        "age_range": "2 a adultos",
        "field_templates": [
            {"key": "vestir", "label": "Vestir"},
            {"key": "alimentacao", "label": "Alimentação"},
            {"key": "higiene", "label": "Higiene pessoal"},
            {"key": "domesticas", "label": "Habilidades domésticas"},
            {"key": "comunidade", "label": "Comunidade"},
        ],
    },
    {
        "id": "tli",
        "name": "TLI",
        "full_name": "Teste de Linguagem Infantil",
        "description": "Avaliação completa das habilidades de linguagem oral em crianças.",
        "age_range": "2 a 6 anos",
        "field_templates": [
            {"key": "fonologia", "label": "Fonologia"},
            {"key": "vocabulario_expressivo", "label": "Vocabulário expressivo"},
            {"key": "vocabulario_receptivo", "label": "Vocabulário receptivo"},
            {"key": "sintaxe", "label": "Sintaxe"},
            {"key": "pragmatica", "label": "Pragmática"},
        ],
    },
    {
        "id": "denver2",
        "name": "Denver II",
        "full_name": "Denver Developmental Screening Test II",
        "description": "Triagem do desenvolvimento infantil.",
        "age_range": "0 a 6 anos",
        "field_templates": [
            {"key": "motor_grosso", "label": "Motor grosso"},
            {"key": "motor_fino", "label": "Motor fino"},
            {"key": "linguagem", "label": "Linguagem"},
            {"key": "pessoal_social", "label": "Pessoal-social"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "bayley3",
        "name": "Bayley-III",
        "full_name": "Bayley Scales of Infant and Toddler Development — 3rd Edition",
        "description": "Escala padronizada para avaliação do desenvolvimento cognitivo, motor e de linguagem.",
        "age_range": "16 dias a 42 meses",
        "field_templates": [
            {"key": "cognicao", "label": "Cognição"},
            {"key": "linguagem_receptiva", "label": "Linguagem receptiva"},
            {"key": "linguagem_expressiva", "label": "Linguagem expressiva"},
            {"key": "motor_fino", "label": "Motor fino"},
            {"key": "motor_grosso", "label": "Motor grosso"},
        ],
    },
    {
        "id": "pard",
        "name": "PARD",
        "full_name": "Protocolo de Avaliação de Risco de Disfagia",
        "description": "Protocolo brasileiro para triagem e avaliação do risco de disfagia.",
        "age_range": "Todos",
        "field_templates": [
            {"key": "historia_clinica", "label": "História clínica"},
            {"key": "sinais_alerta", "label": "Sinais de alerta"},
            {"key": "avaliacao_oral", "label": "Avaliação oral"},
            {"key": "avaliacao_laringe", "label": "Avaliação laringe"},
            {"key": "classificacao_risco", "label": "Classificação de risco"},
        ],
    },
    {
        "id": "fois",
        "name": "FOIS",
        "full_name": "Functional Oral Intake Scale",
        "description": "Escala funcional de ingestão oral em 7 níveis.",
        "age_range": "Todos",
        "field_templates": [
            {"key": "nivel_fois", "label": "Nível FOIS"},
            {"key": "via_alimentacao", "label": "Via de alimentação"},
            {"key": "restricoes", "label": "Restrições"},
            {"key": "aspiracao", "label": "Aspiração"},
        ],
    },
    {
        "id": "eat10",
        "name": "EAT-10",
        "full_name": "Eating Assessment Tool — 10 itens",
        "description": "Questionário de autorrelato para triagem de disfagia.",
        "age_range": "Adultos",
        "field_templates": [
            {"key": "score_total", "label": "Score total"},
            {"key": "item_comprometido", "label": "Item mais comprometido"},
            {"key": "qualidade_vida", "label": "Qualidade de vida"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "doss",
        "name": "DOSS",
        "full_name": "Dysphagia Outcome and Severity Scale",
        "description": "Escala de resultado e gravidade da disfagia.",
        "age_range": "Todos",
        "field_templates": [
            {"key": "nivel_doss", "label": "Nível DOSS"},
            {"key": "consistencias", "label": "Consistências aceitas"},
            {"key": "compensacoes", "label": "Compensações"},
            {"key": "aspiracao", "label": "Aspiração"},
        ],
    },
    {
        "id": "masa",
        "name": "MASA",
        "full_name": "The Mann Assessment of Swallowing Ability",
        "description": "Instrumento padronizado de avaliação clínica da deglutição.",
        "age_range": "Adultos e idosos",
        "field_templates": [
            {"key": "score_total", "label": "Score total"},
            {"key": "risco_aspiracao", "label": "Risco de aspiração"},
            {"key": "consciencia", "label": "Consciência"},
            {"key": "degluticao", "label": "Deglutição"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "mbgr",
        "name": "MBGR",
        "full_name": "Protocolo MBGR (Marchesan, Berretin-Felix, Genaro e Rehder)",
        "description": "Avaliação miofuncional orofacial.",
        "age_range": "3 a 15 anos",
        "field_templates": [
            {"key": "face", "label": "Face"},
            {"key": "labios", "label": "Lábios"},
            {"key": "lingua", "label": "Língua"},
            {"key": "respiracao", "label": "Respiração"},
            {"key": "degluticao", "label": "Deglutição"},
        ],
    },
    {
        "id": "amiofe",
        "name": "AMIOFE",
        "full_name": "Avaliação Miofuncional Orofacial com Escores",
        "description": "Versão com escores numéricos da avaliação miofuncional orofacial.",
        "age_range": "3 a 15 anos",
        "field_templates": [
            {"key": "postura_labios", "label": "Postura de lábios"},
            {"key": "postura_lingua", "label": "Postura de língua"},
            {"key": "respiracao", "label": "Respiração"},
            {"key": "mastigacao", "label": "Mastigação"},
            {"key": "degluticao", "label": "Deglutição"},
        ],
    },
    {
        "id": "omes",
        "name": "OMES",
        "full_name": "Orofacial Myofunctional Evaluation with Scores",
        "description": "Versão internacional padronizada da avaliação miofuncional orofacial.",
        "age_range": "3 a 15 anos",
        "field_templates": [
            {"key": "labios_repouso", "label": "Lábios em repouso"},
            {"key": "tonus_labial", "label": "Tônus labial"},
            {"key": "tonus_lingual", "label": "Tônus lingual"},
            {"key": "respiracao", "label": "Respiração"},
            {"key": "degluticao", "label": "Deglutição"},
        ],
    },
]
