"""Protocol catalog seed data — mirrors frontend mock-data.ts protocolsCatalog."""

PROTOCOLS = [
    {
        "id": "abfw",
        "name": "ABFW",
        "full_name": "Teste de Linguagem Infantil ABFW",
        "description": "Avaliação de fonologia, vocabulário, fluência e pragmática.",
        "age_range": "2 a 12 anos",
        "field_templates": [
            {"key": "fonologia_imitacao", "label": "Fonologia — imitação"},
            {"key": "fonologia_nomeacao", "label": "Fonologia — nomeação"},
            {"key": "vocabulario_expressivo", "label": "Vocabulário expressivo"},
            {"key": "fluencia", "label": "Fluência"},
            {"key": "pragmatica", "label": "Pragmática"},
        ],
    },
    {
        "id": "proc",
        "name": "PROC",
        "full_name": "Protocolo de Observação Comportamental",
        "description": "Observação de comunicação, linguagem e cognição.",
        "age_range": "0 a 6 anos",
        "field_templates": [
            {"key": "formas_comunicacao", "label": "Formas de comunicação"},
            {"key": "funcoes_comunicativas", "label": "Funções comunicativas"},
            {"key": "compreensao_verbal", "label": "Compreensão verbal"},
            {"key": "brincadeira_simbolica", "label": "Brincadeira simbólica"},
            {"key": "imitacao", "label": "Imitação"},
        ],
    },
    {
        "id": "tvip",
        "name": "TVIP",
        "full_name": "Teste de Vocabulário por Imagens Peabody",
        "description": "Avaliação do vocabulário receptivo auditivo.",
        "age_range": "2 a 18 anos",
        "field_templates": [
            {"key": "pontuacao_bruta", "label": "Pontuação bruta"},
            {"key": "idade_equivalente", "label": "Idade equivalente"},
            {"key": "percentil", "label": "Percentil"},
            {"key": "classificacao", "label": "Classificação"},
        ],
    },
    {
        "id": "mchat",
        "name": "M-CHAT-R/F",
        "full_name": "Modified Checklist for Autism in Toddlers — Revised with Follow-Up",
        "description": "Rastreamento de risco para TEA em crianças de 16 a 30 meses (M-CHAT-R + consulta de seguimento).",
        "age_range": "16 a 30 meses",
        "field_templates": [
            {"key": "itens_criticos", "label": "Itens críticos falhados"},
            {"key": "total_falhas", "label": "Total de falhas"},
            {"key": "nivel_risco", "label": "Nível de risco"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "ados2",
        "name": "ADOS-2",
        "full_name": "Autism Diagnostic Observation Schedule — 2nd Edition",
        "description": "Instrumento de observação padronizada para diagnóstico de TEA.",
        "age_range": "12 meses a adultos",
        "field_templates": [
            {"key": "comunicacao", "label": "Comunicação"},
            {"key": "interacao_social", "label": "Interação social recíproca"},
            {"key": "brincadeira", "label": "Brincadeira/imagi. criativa"},
            {"key": "comportamentos_repetitivos", "label": "Comportamentos repetitivos"},
            {"key": "classificacao", "label": "Classificação"},
        ],
    },
    {
        "id": "cars",
        "name": "CARS",
        "full_name": "Childhood Autism Rating Scale",
        "description": "Escala de avaliação do comportamento para diagnóstico e gravidade do autismo infantil.",
        "age_range": "2 a 15 anos",
        "field_templates": [
            {"key": "relacionamento", "label": "Relacionamento com pessoas"},
            {"key": "imitacao", "label": "Imitação"},
            {"key": "resposta_emocional", "label": "Resposta emocional"},
            {"key": "uso_corpo", "label": "Uso do corpo"},
            {"key": "score_total", "label": "Score total"},
        ],
    },
    {
        "id": "vbmapp",
        "name": "VB-MAPP",
        "full_name": "Verbal Behavior Milestones Assessment and Placement Program",
        "description": "Avaliação baseada na ABA para habilidades de linguagem e desenvolvimento.",
        "age_range": "18 meses a 4 anos",
        "field_templates": [
            {"key": "mandos", "label": "Mandos (solicitação)"},
            {"key": "tato", "label": "Tato (nomeação)"},
            {"key": "intraverbal", "label": "Intraverbal"},
            {"key": "listener", "label": "Listener responding"},
            {"key": "barreiras", "label": "Barreiras"},
        ],
    },
    {
        "id": "abllsr",
        "name": "ABLLS-R",
        "full_name": "Assessment of Basic Language and Learning Skills — Revised",
        "description": "Avaliação das habilidades básicas de linguagem e aprendizagem.",
        "age_range": "0 a 12 anos",
        "field_templates": [
            {"key": "receptivas", "label": "Habilidades receptivas"},
            {"key": "motoras", "label": "Habilidades motoras"},
            {"key": "sociais", "label": "Habilidades sociais"},
            {"key": "autoajuda", "label": "Autoajuda"},
            {"key": "leitura", "label": "Leitura"},
        ],
    },
    {
        "id": "tli",
        "name": "TLI",
        "full_name": "Teste de Linguagem Infantil",
        "description": "Avaliação completa das habilidades de linguagem oral em crianças.",
        "age_range": "2 a 6 anos",
        "field_templates": [
            {"key": "fonologia", "label": "Fonologia"},
            {"key": "vocabulario_expressivo", "label": "Vocabulário expressivo"},
            {"key": "vocabulario_receptivo", "label": "Vocabulário receptivo"},
            {"key": "sintaxe", "label": "Sintaxe"},
            {"key": "pragmatica", "label": "Pragmática"},
        ],
    },
    {
        "id": "denver2",
        "name": "Denver II",
        "full_name": "Denver Developmental Screening Test II",
        "description": "Triagem do desenvolvimento infantil.",
        "age_range": "0 a 6 anos",
        "field_templates": [
            {"key": "motor_grosso", "label": "Motor grosso"},
            {"key": "motor_fino", "label": "Motor fino"},
            {"key": "linguagem", "label": "Linguagem"},
            {"key": "pessoal_social", "label": "Pessoal-social"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "bayley3",
        "name": "Bayley-III",
        "full_name": "Bayley Scales of Infant and Toddler Development — 3rd Edition",
        "description": "Escala padronizada para avaliação do desenvolvimento cognitivo, motor e de linguagem.",
        "age_range": "16 dias a 42 meses",
        "field_templates": [
            {"key": "cognicao", "label": "Cognição"},
            {"key": "linguagem_receptiva", "label": "Linguagem receptiva"},
            {"key": "linguagem_expressiva", "label": "Linguagem expressiva"},
            {"key": "motor_fino", "label": "Motor fino"},
            {"key": "motor_grosso", "label": "Motor grosso"},
        ],
    },
    {
        "id": "pard",
        "name": "PARD",
        "full_name": "Protocolo de Avaliação de Risco de Disfagia",
        "description": "Protocolo brasileiro para triagem e avaliação do risco de disfagia.",
        "age_range": "Todos",
        "field_templates": [
            {"key": "historia_clinica", "label": "História clínica"},
            {"key": "sinais_alerta", "label": "Sinais de alerta"},
            {"key": "avaliacao_oral", "label": "Avaliação oral"},
            {"key": "avaliacao_laringe", "label": "Avaliação laringe"},
            {"key": "classificacao_risco", "label": "Classificação de risco"},
        ],
    },
    {
        "id": "fois",
        "name": "FOIS",
        "full_name": "Functional Oral Intake Scale",
        "description": "Escala funcional de ingestão oral em 7 níveis.",
        "age_range": "Todos",
        "field_templates": [
            {"key": "nivel_fois", "label": "Nível FOIS"},
            {"key": "via_alimentacao", "label": "Via de alimentação"},
            {"key": "restricoes", "label": "Restrições"},
            {"key": "aspiracao", "label": "Aspiração"},
        ],
    },
    {
        "id": "adl",
        "name": "ADL",
        "full_name": "Activities of Daily Living — Avaliação Funcional",
        "description": "Avaliação das atividades de vida diária por domínios funcionais.",
        "age_range": "Todas as idades",
        "field_templates": [
            {"key": "autocuidado", "label": "Autocuidado"},
            {"key": "mobilidade", "label": "Mobilidade"},
            {"key": "alimentacao", "label": "Alimentação"},
            {"key": "comunicacao", "label": "Comunicação"},
            {"key": "classificacao_funcional", "label": "Classificação funcional"},
        ],
    },
    {
        "id": "adl-linguagem",
        "name": "ADL 2",
        "full_name": "ADL 2 — Avaliação do Desenvolvimento da Linguagem",
        "description": "Avaliação padronizada de linguagem receptiva e expressiva com escore bruto e EP por faixa etária.",
        "age_range": "12 a 83 meses",
        "field_templates": [
            {"key": "linguagem_compreensiva", "label": "Linguagem Compreensiva (LR)"},
            {"key": "linguagem_expressiva", "label": "Linguagem Expressiva (LE)"},
            {"key": "ep_global", "label": "EP Linguagem Global"},
            {"key": "classificacao", "label": "Classificação"},
        ],
    },
    {
        "id": "eat10",
        "name": "EAT-10",
        "full_name": "Eating Assessment Tool — 10 itens",
        "description": "Questionário de autorrelato para triagem de disfagia.",
        "age_range": "Adultos",
        "field_templates": [
            {"key": "score_total", "label": "Score total"},
            {"key": "item_comprometido", "label": "Item mais comprometido"},
            {"key": "qualidade_vida", "label": "Qualidade de vida"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "doss",
        "name": "DOSS",
        "full_name": "Dysphagia Outcome and Severity Scale",
        "description": "Escala de resultado e gravidade da disfagia.",
        "age_range": "Todos",
        "field_templates": [
            {"key": "nivel_doss", "label": "Nível DOSS"},
            {"key": "consistencias", "label": "Consistências aceitas"},
            {"key": "compensacoes", "label": "Compensações"},
            {"key": "aspiracao", "label": "Aspiração"},
        ],
    },
    {
        "id": "masa",
        "name": "MASA",
        "full_name": "The Mann Assessment of Swallowing Ability",
        "description": "Instrumento padronizado de avaliação clínica da deglutição.",
        "age_range": "Adultos e idosos",
        "field_templates": [
            {"key": "score_total", "label": "Score total"},
            {"key": "risco_aspiracao", "label": "Risco de aspiração"},
            {"key": "consciencia", "label": "Consciência"},
            {"key": "degluticao", "label": "Deglutição"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "mbgr",
        "name": "MBGR",
        "full_name": "Protocolo MBGR (Marchesan, Berretin-Felix, Genaro e Rehder)",
        "description": "Avaliação miofuncional orofacial.",
        "age_range": "3 a 15 anos",
        "field_templates": [
            {"key": "face", "label": "Face"},
            {"key": "labios", "label": "Lábios"},
            {"key": "lingua", "label": "Língua"},
            {"key": "respiracao", "label": "Respiração"},
            {"key": "degluticao", "label": "Deglutição"},
        ],
    },
    {
        "id": "amiofe",
        "name": "AMIOFE-E",
        "full_name": "AMIOFE-E — Avaliação Miofuncional Orofacial com Escores Expandido",
        "description": "Protocolo Felício et al. (2010) — aparência, mobilidade e funções orofaciais com escores 1–4/1–6.",
        "age_range": "Todas as idades",
        "field_templates": [
            {"key": "face", "label": "Face e bochechas"},
            {"key": "labios_lingua", "label": "Lábios e língua"},
            {"key": "mobilidade", "label": "Mobilidade"},
            {"key": "respiracao", "label": "Respiração"},
            {"key": "degluticao", "label": "Deglutição"},
            {"key": "mastigacao", "label": "Mastigação"},
            {"key": "escore_total", "label": "Escore total"},
        ],
    },
    {
        "id": "omes",
        "name": "OMES",
        "full_name": "Orofacial Myofunctional Evaluation with Scores",
        "description": "Versão internacional padronizada da avaliação miofuncional orofacial.",
        "age_range": "3 a 15 anos",
        "field_templates": [
            {"key": "labios_repouso", "label": "Lábios em repouso"},
            {"key": "tonus_labial", "label": "Tônus labial"},
            {"key": "tonus_lingual", "label": "Tônus lingual"},
            {"key": "respiracao", "label": "Respiração"},
            {"key": "degluticao", "label": "Deglutição"},
        ],
    },
    # --- Rastreios e instrumentos operacionais (afeto-clinic-manager) ---
    {
        "id": "portage",
        "name": "Portage",
        "full_name": "Inventário Portage Operacionalizado (IPO) — HCFMRP",
        "description": "Avaliação Portage completa 0-6 anos + Estimulação Infantil. Base HC-FMRP Ribeirão Preto.",
        "age_range": "0 a 6 anos",
        "field_templates": [
            {"key": "socializacao", "label": "Socialização"},
            {"key": "linguagem", "label": "Linguagem"},
            {"key": "autocuidado", "label": "Autocuidado"},
            {"key": "cognicao", "label": "Cognição"},
            {"key": "motor", "label": "Desenvolvimento motor"},
            {"key": "idade_desenvolvimento", "label": "Idade de desenvolvimento"},
        ],
    },
    {
        "id": "snap-iv",
        "name": "SNAP-IV",
        "full_name": "Swanson, Nolan and Pelham Rating Scale — 26 itens",
        "description": "Rastreamento de TDAH e transtorno opositor/desafiador em crianças e adolescentes.",
        "age_range": "6 a 18 anos",
        "field_templates": [
            {"key": "desatencao", "label": "Desatenção (9 itens)"},
            {"key": "hiperatividade", "label": "Hiperatividade/impulsividade (9 itens)"},
            {"key": "oposicao", "label": "Transtorno opositor (8 itens)"},
            {"key": "resultado", "label": "Resultado"},
        ],
    },
    {
        "id": "rastreio-tdah",
        "name": "Rastreio TDAH",
        "full_name": "Rastreio Comportamental de TDAH",
        "description": "Instrumento de rastreio comportamental para sintomas de TDAH.",
        "age_range": "6 a 18 anos",
        "field_templates": [
            {"key": "score_total", "label": "Score total"},
            {"key": "itens_frequentes", "label": "Itens frequentes/muito frequentes"},
            {"key": "nivel_risco", "label": "Nível de risco"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "rastreio-tea",
        "name": "Rastreio TEA",
        "full_name": "Rastreio Comportamental para Transtorno do Espectro Autista",
        "description": "Rastreio em 15 áreas observacionais com escala graduada.",
        "age_range": "2 a 12 anos",
        "field_templates": [
            {"key": "score_total", "label": "Score total"},
            {"key": "areas_destaque", "label": "Áreas em destaque"},
            {"key": "nivel_risco", "label": "Nível de risco"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "asrs",
        "name": "ASRS-5",
        "full_name": "Adult ADHD Self-Report Scale — versão reduzida",
        "description": "Escala de autoavaliação de sintomas de TDAH para adultos.",
        "age_range": "Adultos",
        "field_templates": [
            {"key": "itens_positivos", "label": "Itens positivos (≥2)"},
            {"key": "score_total", "label": "Score total"},
            {"key": "resultado", "label": "Resultado"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "dislexia",
        "name": "Rastreio Dislexia",
        "full_name": "Rastreio de Dislexia",
        "description": "Checklist observacional de sinais de risco para dislexia.",
        "age_range": "6 a 14 anos",
        "field_templates": [
            {"key": "fonologica", "label": "Consciência fonológica"},
            {"key": "leitura", "label": "Leitura"},
            {"key": "escrita", "label": "Escrita"},
            {"key": "compreensao", "label": "Compreensão"},
            {"key": "nivel_risco", "label": "Nível de risco"},
        ],
    },
    {
        "id": "sdq",
        "name": "SDQ",
        "full_name": "Strengths and Difficulties Questionnaire",
        "description": "Questionário de forças e dificuldades emocionais e comportamentais.",
        "age_range": "4 a 17 anos",
        "field_templates": [
            {"key": "emocional", "label": "Sintomas emocionais"},
            {"key": "conduta", "label": "Problemas de conduta"},
            {"key": "hiperatividade", "label": "Hiperatividade"},
            {"key": "pares", "label": "Problemas com pares"},
            {"key": "prosocial", "label": "Comportamento pró-social"},
            {"key": "total_dificuldades", "label": "Total de dificuldades"},
        ],
    },
    {
        "id": "vanderbilt",
        "name": "Vanderbilt",
        "full_name": "Vanderbilt ADHD Diagnostic Parent Rating Scale (NICHQ)",
        "description": "Triagem de TDAH com avaliação de desempenho escolar.",
        "age_range": "6 a 12 anos",
        "field_templates": [
            {"key": "desempenho", "label": "Desempenho escolar"},
            {"key": "desatencao", "label": "Desatenção"},
            {"key": "hiperatividade", "label": "Hiperatividade/impulsividade"},
            {"key": "resultado", "label": "Resultado"},
        ],
    },
    {
        "id": "ata",
        "name": "ATA",
        "full_name": "Triagem de Traços Autísticos",
        "description": "Checklist de traços relacionados ao espectro autista.",
        "age_range": "2 a 12 anos",
        "field_templates": [
            {"key": "social", "label": "Interação social"},
            {"key": "comunicacao", "label": "Comunicação"},
            {"key": "repetitivo", "label": "Comportamentos repetitivos"},
            {"key": "score_total", "label": "Score total"},
            {"key": "resultado", "label": "Resultado"},
        ],
    },
    {
        "id": "desenvolvimento-infantil",
        "name": "Desenv. Infantil",
        "full_name": "Rastreio de Desenvolvimento Infantil",
        "description": "Marcos do desenvolvimento por faixa etária (0–6 anos).",
        "age_range": "0 a 6 anos",
        "field_templates": [
            {"key": "faixa_etaria", "label": "Faixa etária aplicada"},
            {"key": "marcos_nao_atingidos", "label": "Marcos não atingidos"},
            {"key": "alerta", "label": "Alerta clínico"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "habilidades-sociais",
        "name": "Hab. Sociais",
        "full_name": "Rastreio de Habilidades Sociais",
        "description": "Checklist observacional de habilidades sociais em 6 domínios.",
        "age_range": "4 a 18 anos",
        "field_templates": [
            {"key": "indicadores_baixos", "label": "Indicadores baixos (≤1)"},
            {"key": "dominios", "label": "Domínios comprometidos"},
            {"key": "score_total", "label": "Score total"},
            {"key": "resultado", "label": "Resultado"},
        ],
    },
    {
        "id": "desempenho-escolar",
        "name": "Desempenho Escolar",
        "full_name": "Avaliação de Desempenho Escolar",
        "description": "Avaliação estruturada do desempenho acadêmico e habilidades de aprendizagem.",
        "age_range": "6 a 14 anos",
        "field_templates": [
            {"key": "media_funcionamento", "label": "Média de funcionamento"},
            {"key": "areas_destaque", "label": "Áreas em destaque"},
            {"key": "classificacao", "label": "Classificação"},
            {"key": "conduta", "label": "Conduta"},
        ],
    },
    {
        "id": "spm",
        "name": "SPM",
        "full_name": "Sensory Processing Measure",
        "description": "Bateria de processamento sensorial e praxis com normas brasileiras.",
        "age_range": "4 meses a 12 anos",
        "field_templates": [
            {"key": "participacao_social", "label": "Participação social (SOC)"},
            {"key": "visual", "label": "Visual (VIS)"},
            {"key": "auditivo", "label": "Auditivo (AUD)"},
            {"key": "tato", "label": "Tato (TOQ)"},
            {"key": "corpo", "label": "Consciência corporal (CC)"},
            {"key": "equilibrio", "label": "Equilibrio e movimento (EQU)"},
            {"key": "planejamento", "label": "Planejamento e ideacao (PLA)"},
            {"key": "resultado", "label": "Resultado geral"},
        ],
    },
]
