"""ADL 2 item catalog — titles and age bands (Manual Examinador A2 + Protocolo)."""

from __future__ import annotations

AGE_BANDS = [
    ("12-17", 12, 17),
    ("18-23", 18, 23),
    ("24-29", 24, 29),
    ("30-35", 30, 35),
    ("36-41", 36, 41),
    ("42-47", 42, 47),
    ("48-53", 48, 53),
    ("54-59", 54, 59),
    ("60-65", 60, 65),
    ("66-71", 66, 71),
    ("72-77", 72, 77),
    ("78-83", 78, 83),
]

# Linguagem Expressiva — item_number → (age_start, age_end, title)
LE_ITEMS: dict[int, tuple[int, int, str]] = {
    1: (12, 17, "Participa de brincadeiras com outra pessoa pelo período de 1 a 2 minutos."),
    2: (12, 17, "Comunica-se de forma gestual."),
    3: (12, 17, "A criança vocaliza sem que movimentos de pernas e de braços acompanhem a emissão dos sons."),
    4: (12, 17, "Emite sequências de duas sílabas."),
    5: (12, 17, "Tem vocabulário de pelo menos uma palavra."),
    6: (12, 17, "Faz turnos durante uma brincadeira."),
    7: (12, 17, "Imita uma variedade de sons (fonemas)."),
    8: (18, 23, "Comunicação da criança através de vocalizações e de gestos para obter um objeto."),
    9: (18, 23, "Imita uma palavra."),
    10: (18, 23, "Produz sequências de palavras."),
    11: (18, 23, "Tem vocabulário expressivo (espontâneo) de cinco a dez palavras."),
    12: (18, 23, "A criança fala sequência de palavras sem significado com entonação semelhante a do adulto (jargão)."),
    13: (24, 29, "A criança usa palavras com intenção de se comunicar."),
    14: (24, 29, "Combina duas ou mais palavras com significado."),
    15: (24, 29, "Nomeia figuras."),
    16: (24, 29, "Comunica-se mais por palavras do que por gestos."),
    17: (30, 35, "Combina três ou quatro palavras na fala espontânea."),
    18: (30, 35, "Responde com substantivo indicando posse."),
    19: (30, 35, "Vocabulário expressivo."),
    20: (36, 41, "Usa a forma de verbo no gerúndio."),
    21: (36, 41, 'Compreende e responde a questões com: "o que" substantivo; advérbio interrogativo "onde" e de negação "não".'),
    22: (36, 41, "Nomeia cores."),
    23: (36, 41, "Usa diferentes combinações de palavras para se expressar."),
    24: (42, 47, "Usa palavras que expressam relação espacial."),
    25: (42, 47, "Conceito de quantidade."),
    26: (42, 47, "Habilidade para solucionar e responder a questões sobre situações do cotidiano."),
    27: (42, 47, "Descreve ações em uma sequência de figuras."),
    28: (48, 53, "Responde a perguntas sobre as suas atividades na escola (no colégio)."),
    29: (48, 53, "Habilidade para descrever o uso de objetos."),
    30: (48, 53, 'Responde a questões com o advérbio de lugar "onde".'),
    31: (48, 53, "Usa pronome possessivo."),
    32: (48, 53, "Expressa quantidade."),
    33: (54, 59, "Produz orações semanticamente corretas."),
    34: (54, 59, "Plural regular."),
    35: (54, 59, "Usa verbo no tempo passado."),
    36: (54, 59, "Expressa quantidade."),
    37: (54, 59, "Completa analogias."),
    38: (60, 65, "Categorização de nomes."),
    39: (60, 65, "Responde a questões sobre os motivos das ações realizadas em sua rotina diária."),
    40: (60, 65, "Utiliza adjetivos para descrever pessoas e objetos."),
    41: (60, 65, "Compreende e descreve similaridade entre objetos."),
    42: (60, 65, "Memória para repetir sentenças."),
    43: (60, 65, "Descreve ações em uma sequência de figuras."),
    44: (60, 65, "Responde a perguntas diante de uma sequência de figuras."),
    45: (66, 71, "Expressa quantidade."),
    46: (66, 71, "Habilidade para buscar palavras dentro de uma categoria semântica."),
    47: (66, 71, "Produz uma história diante de uma gravura."),
    48: (66, 71, "Relembra sentenças em um contexto."),
    49: (72, 77, "Produz uma história diante a uma sequência de figuras."),
    50: (72, 77, "Habilidade para definir palavras."),
    51: (72, 77, "Relembrando sentenças em um contexto."),
    52: (72, 77, "Produz uma história diante de uma sequência de gravuras."),
    53: (72, 77, "Reconta uma história com apoio visual."),
    54: (78, 83, "Relembra e descreve situações da sua rotina diária."),
    55: (78, 83, "Relembra sentenças em um contexto."),
    56: (78, 83, "Produz uma história diante de uma sequência de gravuras."),
    57: (78, 83, "Faz cálculo de soma e subtração até 5."),
    58: (78, 83, "Identifica e nomeia letras."),
}

# Linguagem Compreensiva — items 3–52 (1–2 são pré-requisitos de atenção)
LR_ITEMS: dict[int, tuple[int, int, str]] = {
    3: (12, 17, "Vocabulário compreensivo. Identifica objetos familiares."),
    4: (12, 17, "Compreende pedidos verbais simples com pistas gestuais."),
    5: (18, 23, "Vocabulário receptivo. Identifica figuras de objetos."),
    6: (18, 23, "Compreende ordens simples com dois pedidos."),
    7: (18, 23, "Compreende palavras inibitórias."),
    8: (18, 23, "Compreende verbos dentro de um contexto."),
    9: (24, 29, "Usa apropriadamente objetos familiares enquanto brinca."),
    10: (24, 29, "Identifica partes do corpo em si ou na boneca."),
    11: (24, 29, "Compreende relação espacial."),
    12: (24, 29, "Compreende alguns pronomes."),
    13: (24, 29, "Reconhece a ação nas figuras."),
    14: (30, 35, 'Compreende os pronomes "mim", "seu", "minha".'),
    15: (30, 35, "Compreende o uso dos objetos."),
    16: (30, 35, "Compreende os conceitos dos adjetivos."),
    17: (36, 41, "Compreende relações parte/todo."),
    18: (36, 41, "Compreende conceitos de quantidade."),
    19: (36, 41, "Identifica cores."),
    20: (36, 41, "Identifica categorias de objetos em figuras."),
    21: (42, 47, "Compreende conceito de quantidade."),
    22: (42, 47, "Compreende pronomes pessoais."),
    23: (42, 47, "Faz deduções."),
    24: (42, 47, "Compreende o conceito de subir."),
    25: (42, 47, 'Compreende questões com o pronome interrogativo "que".'),
    26: (48, 53, "Compreende perguntas negativas."),
    27: (48, 53, "Conceito de exclusão e inclusão."),
    28: (48, 53, "Compreende conceitos de tempo."),
    29: (48, 53, "Compreende conceitos de adjetivos."),
    30: (48, 53, "Compreende conceitos espaciais."),
    31: (54, 59, "Compreende conceitos de adjetivos."),
    32: (54, 59, "Compreende analogias."),
    33: (54, 59, 'Compreende orações com o pronome relativo "que".'),
    34: (54, 59, "Compreende conceito de velocidade."),
    35: (60, 65, "Compreende conceitos de adjetivos comparativos."),
    36: (60, 65, "Compreende orações com adjetivos."),
    37: (60, 65, "Compreende os sufixos de gênero."),
    38: (60, 65, "Compreende conceito de quantidade."),
    39: (66, 71, "Compreende conceitos de adjetivos."),
    40: (66, 71, "Compreende palavras que indicam relação espacial."),
    41: (66, 71, "Compreende classificação semântica."),
    42: (66, 71, "Compreende conceitos de quantidade."),
    43: (72, 77, "Relação temporal/sequência."),
    44: (72, 77, "Relação espacial."),
    45: (72, 77, "Identifica sons iniciais das palavras."),
    46: (72, 77, "Relação temporal."),
    47: (72, 77, "Relação temporal/sequência."),
    48: (78, 83, "Compreende conceitos de quantidade."),
    49: (78, 83, "Compreende sentenças na voz passiva."),
    50: (78, 83, "Aliteração."),
    51: (78, 83, "Rima."),
    52: (78, 83, "Combinação de sons."),
}

PREREQ_ITEMS = [
    {
        "id": "pre_01",
        "item_number": 1,
        "domain": "PRE",
        "text": "Atenção visual.",
        "age_start_months": 12,
        "age_end_months": 83,
    },
    {
        "id": "pre_02",
        "item_number": 2,
        "domain": "PRE",
        "text": "Atenção auditiva.",
        "age_start_months": 12,
        "age_end_months": 83,
    },
]
